host: 0.0.0.0
port: 5000

# define duration between each dashboard rotation (ms)
rotationDuration: 8000

# This part of the config is neither watched nor
# transmitted to the UI as it might contain sensible info
apis:
  # define the global interval used by Mozaïk Bus to call registered APIs
  pollInterval: 100000

extension: &extension gitlab
gitlabProject: &gitlabProject gitlab-org/gitlab-runner

dashboards:
- title:   '@mozaik/ext-gitlab demo'
  columns: 4
  rows:    6
  widgets:
    -
      extension: *extension
      widget:    Project
      project:   *gitlabProject
      columns:   1
      rows:      2
      x:         0
      y:         0
    -
      extension: *extension
      widget:    ProjectMembers
      project:   *gitlabProject
      columns:   1
      rows:      2
      x:         1
      y:         3
    -
      extension: *extension
      widget:    ProjectContributors
      project:   *gitlabProject
      columns:   1
      rows:      2
      x:         2
      y:         3
    -
      extension: *extension
      widget:    ProjectActivity
      project:   *gitlabProject
      columns:   1
      rows:      4
      x:         0
      y:         2
    -
      extension: *extension
      widget:    Branches
      project:   *gitlabProject
      columns:   1
      rows:      4
      x:         3
      y:         2
    -
      extension: *extension
      widget:    JobHistogram
      project:   *gitlabProject
      columns:   2
      rows:      2
      x:         1
      y:         0
    -
      extension:    mozaik
      widget:       Inspector
      columns:      1
      rows:         2
      x:            3
      y:            0
    -
      extension:         *extension
      widget:            LatestProjectPipeline
      project:           *gitlabProject
      gitRef:            master
      hideCommitMessage: true
      columns:           2
      rows:              1
      x:                 1
      y:                 2
    -
      extension:         *extension
      widget:            LatestProjectPipeline
      project:           *gitlabProject
      gitRef:            runner-self-signed-docs
      hideCommitMessage: false
      columns:           2
      rows:              1
      x:                 1
      y:                 5
